### PR TITLE
added bootstrap-css. modified template files to use bootstrap. modified readme with oauth github steps

### PR DESCRIPTION
**Pull request by arron-green**

### CODE REVIEW

**Comment by thisgeek** [comment]
Yay, styles!

Is it possible to clean up those five "Merge branch 'master' of https://github.com/digitalsalon/meetdownjs" commits? Perhaps with a rebase?

**Comment by arron-green** [comment]
so the merge's are with kenbolton.  Is he the one to clean that up or is it me?

**Comment by thisgeek** [comment]
This is because you originally forked off of the @kenbolton repo, right? Apply your changes on top of the latest for the digitalsalon/master and resubmit the pull request. And I'll tell ken to clean up his repo. :)

**Comment by thisgeek** [comment]
Perfer: #19

**Pull request closed without merging**
